### ISSUE TITLE
Contract to call other contract

### ISSUE THREAD

**Issue by thith** [TradaTech/icetea#2]
Something like this:
```js
@contract Contract1 {
  @state otherContract;
  constructor(other) {this.otherContract = other}
  test() {
      const contract = loadContract(this.otherContract);
      contract.callSomeFunction(someParams);
  }
}
```

1. Worker pass loadContract to Context
2. Context pass it to getEnv()

**NOTE**
1. The context passed to callee contract should be different, for example msg.sender should be the caller contract address, etc.
2. Have to review about security to ensure callee could not do things not allow

Checklist:
- [x] getEnv() return a loadContract function (Worker should provide necessary weapon to Context to make loadContract works)
- [x] returned Contract could be used to call
- [x] Set msg.sender to original contract
- [x] Should have some way to pass the context to the callee Contract
- [x] Review state security (transaction, view, etc.)

**Comment by thith** [comment]
@Sotatek-DucPham Should add 2 test cases:
- contract A => contract B => contract C: check if msg.sender inside C is B
- view method calls transaction method

**Comment by Sotatek-DucPham** [comment]
Test Doned. TODO: test script

**Comment by thith** [comment]
@Sotatek-DucPham This make _transaction method_ cannot call _view method_ of other contract.
I suggest we let the caller specify that:
```js
// To call a view function
contract.call('methodName', params);

// To call a transaction
contract.send('methodName', params);
```

It is not very elegant. We could have some improvement for 'JS decorated' contract later by declaring some kind of interface in the future. But do not do it now. For 'raw JS', the above is enough.

In addition, inside Proxy, no need to check for `real` method. Because it is Proxy over `{}` and have no method. Even if it has, we should not call it.

**Comment by Sotatek-DucPham** [comment]
For `real` method, I want to add a `contract.address` later, it is not a method. The code is for preparation only.

**Comment by thith** [comment]
Or we might adopt web3-like syntax:
```js
// To call a view function
contract.methodName(params).call() // or invokeView(), later we'll have invokePure()

// To call a transaction
contract.methodName(params).send() // or invokeTx()
```

**Comment by Sotatek-DucPham** [comment]
I've reviewed the solidity. A `transaction` method can call a `view` method.

**Comment by thith** [comment]
> I've reviewed the solidity. A `transaction` method can call a `view` method.

@Sotatek-DucPham Did you finish this part (for JS)? If yes, let's make a pull request.

**Comment by Sotatek-DucPham** [comment]
It is in `feature/call_contracts`, You merged
